{{- /* Inform-only: the bucket has been provisioned. */ -}}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .Parameters.claimName }}
  namespace: {{ .Parameters.namespace }}
status:
  phase: Bound
