apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: policystack
  namespace: openshift-gitops
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - clusters:
                    selector:
                      matchExpressions:
                        - key: clusterID
                          operator: Exists
                - git:
                    repoURL: 'https://github.com/PolicyStack/PolicyStack.git'
                    revision: HEAD
                    pathParamPrefix: fleet
                    files:
                    - path: 'fleet/{{if index .metadata.labels "local-cluster"}}hubs/acm-dc1{{else}}{{.name}}{{end}}.yaml'
          - git:
              repoURL: 'https://github.com/PolicyStack/PolicyStack.git'
              revision: '{{.revision}}'
              directories:
              - path: 'stack/*'
  template:
    metadata:
      name: '{{.path.basenameNormalized}}-{{.name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/PolicyStack/PolicyStack.git'
        targetRevision: '{{.revision}}'
        path: '{{.path.path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: open-cluster-management
      syncPolicy:
        syncOptions:
        - RespectIgnoreDifferences=true
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    {{- $name := .name }}
    {{- if index .metadata.labels "local-cluster" }}
      {{- $name = "acm-dc1" }}
    metadata:
      name: '{{.path.basenameNormalized}}-{{ $name }}'
    {{- end }}

    spec:
      source:
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
          - values.yaml
          - ../../values.yaml
          {{- range index . "valueFiles" }}
          - ../../values/{{ . }}
          {{- end }}
          - ../../values/clusters/{{ $name }}.yaml
          valuesObject:
            selectedName: {{ $name }}
            selectedId: {{ .metadata.labels.clusterID }}
            selector:
              matchExpressions:
                name:
                  key: name
                  operator: In
                  values:
                    - {{ .name | quote }}
