{{- /*
Lets the remediation aggregator patch ComplianceRemediation objects. The Role and RoleBinding are
separate converters because a PolicyStack converter renders one object.
*/ -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: compliance-operator-agg-patch-role
  namespace: {{ .Parameters.namespace }}
rules:
  - apiGroups:
      - compliance.openshift.io
    resources:
      - complianceremediations
      - complianceremediations/status
    verbs: [create, get, update, patch, delete]
