{{- /* Requests a NooBaa bucket from ODF for AAP's hub content storage. */ -}}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .Parameters.bucketName }}
  namespace: {{ .Parameters.namespace }}
spec:
  generateBucketName: {{ .Parameters.bucketName }}
  storageClassName: {{ .Parameters.bucketStorageClass }}
